//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassengersAge
    {
        public string ID { get; set; }
        public string TripId { get; set; }
        public string Value { get; set; }
    
        public virtual Trip Trip { get; set; }
    }
}
