
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Infrastructure.DataAccess
{

using System;
    using System.Collections.Generic;
    
public partial class Passenger
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Passenger()
    {

        this.Trips = new HashSet<Trip>();

    }


    public int CID { get; set; }

    public string First_name { get; set; }

    public string Last_name { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public string Password { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Trip> Trips { get; set; }

}

}
