//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Route()
        {
            this.TransitDetails = new HashSet<TransitDetail>();
        }
    
        public string ID { get; set; }
        public string TripID { get; set; }
        public string Distance { get; set; }
        public string Duration { get; set; }
        public string Travel_mode { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Seats { get; set; }
    
        public virtual Trip Trip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransitDetail> TransitDetails { get; set; }
    }
}
