//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trip()
        {
            this.PassengersAges = new HashSet<PassengersAge>();
            this.Routes = new HashSet<Route>();
        }
    
        public string ID { get; set; }
        public int PassengerCID { get; set; }
        public Nullable<System.DateTime> Arrival_time { get; set; }
        public Nullable<System.DateTime> Departure_time { get; set; }
        public string Start_address { get; set; }
        public string End_address { get; set; }
        public string Distance { get; set; }
        public string Duration { get; set; }
        public string Preference { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Status { get; set; }
    
        public virtual Passenger Passenger { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PassengersAge> PassengersAges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Route> Routes { get; set; }
    }
}
